version: "3.4"

services:
  denunciar:
    build: ./backend/
    container_name: denunciar
    env_file:
      - backend/.env
    environment:
      - WAIT_HOSTS=denunciar-db:5432
    ports:
      - "5858:9229"
      - "8080:8080"
    volumes:
      - ./backend/src:/usr/local/src:ro
    networks:
      - denunciar
    depends_on:
      - denunciar-db

  denunciar-db:
    image: postgres:12-alpine
    container_name: denunciar-db
    env_file:
      - backend/.env
    ports:
      - "35432:5432"
    networks:
      - denunciar

  denunciar-front:
    build: ./frontend/
    container_name: denunciar-front
    image: denunciar-front
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/dist/frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  denunciar:
